name: flutter_calcimc_prova2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  sqflite: ^2.4.2
  intl: any  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

  fonts:
  - family: Stock
    fonts:
      - asset: assets/fonts/Dead Stock - Demo.ttf

